@server=http://localhost:4004


### Employees
# @name Employees_GET
GET {{server}}/odata/v4/be-cash/Employees



### Employees
# @name Employees_POST
POST {{server}}/odata/v4/be-cash/Employees
Content-Type: application/json

{
  "ID": "42844523-a743-479e-b673-5d144b302fde",
  "firstName": "firstName-4284452",
  "lastName": "lastName-4284452",
  "email": "email-4284452",
  "isActive": true,
  "weeklyTargetHours": 8.54,
  "position": {
    "name": "Junior"
  },
  "loggedHours": [
    {
      "ID": "11786288-3f89-4b2a-b920-cd277f076e4a",
      "quantity": 24.1545675401217,
      "project": {
        "ID": "27640625-32a0-40a7-8694-6f4b4638a5f9"
      },
      "imputationDate": "2012-09-25",
      "status": "Approved",
      "rejectionReason": "Lack of hours",
      "isLocked": true,
      "isModifiedByAdmin": true,
      "modificationDate": "2002-01-01T00:00:00.000Z"
    },
    {
      "ID": "11786289-b88d-47f3-87f7-bc4a3842a10e",
      "quantity": 61.171034151643276,
      "project": {
        "ID": "29782225-94aa-4653-bc69-f4bdd967eb8d"
      },
      "imputationDate": "2021-10-23",
      "status": "Pending",
      "rejectionReason": "Not rejected",
      "isLocked": false,
      "isModifiedByAdmin": false,
      "modificationDate": "2021-06-09T00:00:00.000Z"
    }
  ],
  "projects": [
    {
      "project": {
        "ID": "29782225-94aa-4653-bc69-f4bdd967eb8d"
      }
    }
  ],
  "employeeName": "employeeName-4284452"
}


### Employees
# @name Employees_PATCH
PATCH {{server}}/odata/v4/be-cash/Employees/42844523-a743-479e-b673-5d144b302fde
Content-Type: application/json

{
  "ID": "42844523-a743-479e-b673-5d144b302fde",
  "firstName": "firstName-4284452",
  "lastName": "lastName-4284452",
  "email": "email-4284452",
  "isActive": true,
  "weeklyTargetHours": 8.54,
  "position": {
    "name": "Junior"
  },
  "loggedHours": [
    {
      "ID": "11786288-3f89-4b2a-b920-cd277f076e4a",
      "quantity": 24.1545675401217,
      "project": {
        "ID": "27640625-32a0-40a7-8694-6f4b4638a5f9"
      },
      "imputationDate": "2012-09-25",
      "status": "Approved",
      "rejectionReason": "Lack of hours",
      "isLocked": true,
      "isModifiedByAdmin": true,
      "modificationDate": "2002-01-01T00:00:00.000Z"
    },
    {
      "ID": "11786289-b88d-47f3-87f7-bc4a3842a10e",
      "quantity": 61.171034151643276,
      "project": {
        "ID": "29782225-94aa-4653-bc69-f4bdd967eb8d"
      },
      "imputationDate": "2021-10-23",
      "status": "Pending",
      "rejectionReason": "Not rejected",
      "isLocked": false,
      "isModifiedByAdmin": false,
      "modificationDate": "2021-06-09T00:00:00.000Z"
    }
  ],
  "projects": [
    {
      "project": {
        "ID": "29782225-94aa-4653-bc69-f4bdd967eb8d"
      }
    }
  ],
  "employeeName": "employeeName-4284452"
}


### Employees
# @name Employees_DELETE
DELETE {{server}}/odata/v4/be-cash/Employees/42844523-a743-479e-b673-5d144b302fde
Content-Type: application/json


### Positions
# @name Positions_GET
GET {{server}}/odata/v4/be-cash/Positions



### Positions
# @name Positions_POST
POST {{server}}/odata/v4/be-cash/Positions
Content-Type: application/json

{
  "name": "Junior",
  "billing": 116.2
}


### Positions
# @name Positions_PATCH
PATCH {{server}}/odata/v4/be-cash/Positions/Junior
Content-Type: application/json

{
  "name": "Junior",
  "billing": 116.2
}


### Positions
# @name Positions_DELETE
DELETE {{server}}/odata/v4/be-cash/Positions/Junior
Content-Type: application/json


### LoggedHours
# @name LoggedHours_GET
GET {{server}}/odata/v4/be-cash/LoggedHours



### LoggedHours
# @name LoggedHours_POST
POST {{server}}/odata/v4/be-cash/LoggedHours
Content-Type: application/json

{
  "ID": "11786288-3f89-4b2a-b920-cd277f076e4a",
  "quantity": 24.1545675401217,
  "project": {
    "ID": "27640625-32a0-40a7-8694-6f4b4638a5f9"
  },
  "imputationDate": "2012-09-25",
  "status": "Approved",
  "rejectionReason": "Lack of hours",
  "isLocked": true,
  "isModifiedByAdmin": true,
  "modificationDate": "2002-01-01T00:00:00.000Z"
}


### LoggedHours
# @name LoggedHours_PATCH
PATCH {{server}}/odata/v4/be-cash/LoggedHours/11786288-3f89-4b2a-b920-cd277f076e4a
Content-Type: application/json

{
  "ID": "11786288-3f89-4b2a-b920-cd277f076e4a",
  "quantity": 24.1545675401217,
  "project": {
    "ID": "27640625-32a0-40a7-8694-6f4b4638a5f9"
  },
  "imputationDate": "2012-09-25",
  "status": "Approved",
  "rejectionReason": "Lack of hours",
  "isLocked": true,
  "isModifiedByAdmin": true,
  "modificationDate": "2002-01-01T00:00:00.000Z"
}


### LoggedHours
# @name LoggedHours_DELETE
DELETE {{server}}/odata/v4/be-cash/LoggedHours/11786288-3f89-4b2a-b920-cd277f076e4a
Content-Type: application/json


### Projects
# @name Projects_GET
GET {{server}}/odata/v4/be-cash/Projects



### Projects
# @name Projects_POST
POST {{server}}/odata/v4/be-cash/Projects
Content-Type: application/json

{
  "ID": "27640625-32a0-40a7-8694-6f4b4638a5f9",
  "name": "name-27640625",
  "client": {
    "ID": "26418437-cd9a-4fc0-b1cf-b786297ef39b"
  },
  "employeesAssigned": [
    {
      "employee": {
        "ID": "42844523-a743-479e-b673-5d144b302fde"
      }
    }
  ],
  "managerOnCharge": {
    "ID": "42844523-a743-479e-b673-5d144b302fde"
  },
  "status": "Testing",
  "initialBudget": 6540109805104.5,
  "closedAt": "2015-01-29T00:00:00.000Z",
  "reportSentToClient": false
}


### Projects
# @name Projects_PATCH
PATCH {{server}}/odata/v4/be-cash/Projects/27640625-32a0-40a7-8694-6f4b4638a5f9
Content-Type: application/json

{
  "ID": "27640625-32a0-40a7-8694-6f4b4638a5f9",
  "name": "name-27640625",
  "client": {
    "ID": "26418437-cd9a-4fc0-b1cf-b786297ef39b"
  },
  "employeesAssigned": [
    {
      "employee": {
        "ID": "42844523-a743-479e-b673-5d144b302fde"
      }
    }
  ],
  "managerOnCharge": {
    "ID": "42844523-a743-479e-b673-5d144b302fde"
  },
  "status": "Testing",
  "initialBudget": 6540109805104.5,
  "closedAt": "2015-01-29T00:00:00.000Z",
  "reportSentToClient": false
}


### Projects
# @name Projects_DELETE
DELETE {{server}}/odata/v4/be-cash/Projects/27640625-32a0-40a7-8694-6f4b4638a5f9
Content-Type: application/json


### Clients
# @name Clients_GET
GET {{server}}/odata/v4/be-cash/Clients



### Clients
# @name Clients_POST
POST {{server}}/odata/v4/be-cash/Clients
Content-Type: application/json

{
  "ID": "26418437-cd9a-4fc0-b1cf-b786297ef39b",
  "name": "name-26418437",
  "email": "email-26418437",
  "isActive": false,
  "projects": [
    {
      "ID": "2978221e-dba0-41a4-97e0-7ddceb9ca574",
      "name": "name-2978221",
      "employeesAssigned": [
        {
          "employee": {
            "ID": "42844523-a743-479e-b673-5d144b302fde"
          }
        }
      ],
      "managerOnCharge": {
        "ID": "42844523-a743-479e-b673-5d144b302fde"
      },
      "status": "Closed",
      "initialBudget": 4913890141773.88,
      "closedAt": "2007-11-11T00:00:00.000Z",
      "reportSentToClient": false
    },
    {
      "ID": "29782225-94aa-4653-bc69-f4bdd967eb8d",
      "name": "name-2978222",
      "employeesAssigned": [
        {
          "employee": {
            "ID": "42844523-a743-479e-b673-5d144b302fde"
          }
        }
      ],
      "managerOnCharge": {
        "ID": "42844523-a743-479e-b673-5d144b302fde"
      },
      "status": "Open",
      "initialBudget": 4306895246449.81,
      "closedAt": "2001-06-19T00:00:00.000Z",
      "reportSentToClient": true
    }
  ]
}


### Clients
# @name Clients_PATCH
PATCH {{server}}/odata/v4/be-cash/Clients/26418437-cd9a-4fc0-b1cf-b786297ef39b
Content-Type: application/json

{
  "ID": "26418437-cd9a-4fc0-b1cf-b786297ef39b",
  "name": "name-26418437",
  "email": "email-26418437",
  "isActive": false,
  "projects": [
    {
      "ID": "2978221e-dba0-41a4-97e0-7ddceb9ca574",
      "name": "name-2978221",
      "employeesAssigned": [
        {
          "employee": {
            "ID": "42844523-a743-479e-b673-5d144b302fde"
          }
        }
      ],
      "managerOnCharge": {
        "ID": "42844523-a743-479e-b673-5d144b302fde"
      },
      "status": "Closed",
      "initialBudget": 4913890141773.88,
      "closedAt": "2007-11-11T00:00:00.000Z",
      "reportSentToClient": false
    },
    {
      "ID": "29782225-94aa-4653-bc69-f4bdd967eb8d",
      "name": "name-2978222",
      "employeesAssigned": [
        {
          "employee": {
            "ID": "42844523-a743-479e-b673-5d144b302fde"
          }
        }
      ],
      "managerOnCharge": {
        "ID": "42844523-a743-479e-b673-5d144b302fde"
      },
      "status": "Open",
      "initialBudget": 4306895246449.81,
      "closedAt": "2001-06-19T00:00:00.000Z",
      "reportSentToClient": true
    }
  ]
}


### Clients
# @name Clients_DELETE
DELETE {{server}}/odata/v4/be-cash/Clients/26418437-cd9a-4fc0-b1cf-b786297ef39b
Content-Type: application/json


### EmployeesAssigned
# @name EmployeesAssigned_GET
GET {{server}}/odata/v4/be-cash/EmployeesAssigned



### EmployeesAssigned
# @name EmployeesAssigned_POST
POST {{server}}/odata/v4/be-cash/EmployeesAssigned
Content-Type: application/json

{
  "employee": {
    "ID": "42844523-a743-479e-b673-5d144b302fde"
  }
}


### EmployeesAssigned
# @name EmployeesAssigned_PATCH
PATCH {{server}}/odata/v4/be-cash/EmployeesAssigned(employee=[object Object],project=[object Object])
Content-Type: application/json

{
  "employee": {
    "ID": "42844523-a743-479e-b673-5d144b302fde"
  }
}


### EmployeesAssigned
# @name EmployeesAssigned_DELETE
DELETE {{server}}/odata/v4/be-cash/EmployeesAssigned(employee=[object Object],project=[object Object])
Content-Type: application/json


### EmployeeProjectHoursView
# @name EmployeeProjectHoursView_GET
GET {{server}}/odata/v4/be-cash/EmployeeProjectHoursView



### EmployeeHoursStatusView
# @name EmployeeHoursStatusView_GET
GET {{server}}/odata/v4/be-cash/EmployeeHoursStatusView



### ManagerProjectFinancesView
# @name ManagerProjectFinancesView_GET
GET {{server}}/odata/v4/be-cash/ManagerProjectFinancesView



### SpentPerPositionView
# @name SpentPerPositionView_GET
GET {{server}}/odata/v4/be-cash/SpentPerPositionView



### ProjectBudgetProjectionView
# @name ProjectBudgetProjectionView_GET
GET {{server}}/odata/v4/be-cash/ProjectBudgetProjectionView

